### ISSUE TITLE
Issue in loading config values

### ISSUE THREAD

**Issue by sreekuttan-m-achari** [prologuetech/laravel-big#1]
In  vendor/prologuetech/big/src/Big.php , env values are not getting loaded .. ! 

```
$googleService = new ServiceBuilder([
				'keyFilePath' => config('prologue-big.big.auth_file'),
				'projectId'   => config('prologue-big.big.project_id'),
			]);
``` 
resulting in this error 

 Google \ Cloud \ Core \ Exception \ GoogleException
No project ID was provided, and we were unable to detect a default project ID.

It was able to execute properly after we copied the '/vendor/prologuetech/big/config/prologue-big.php' file    to '/config/prologue-big.php'

is this an issue or any other mistakes in installing/loading the package causing this ? Please guide

**Comment by Medalink** [comment]
Running the vendor publish command should place your config file for you:

`php artisan vendor:publish --provider=Prologuetech\Big`

Did this not place the file?

**Comment by sreekuttan-m-achari** [comment]
Yes we did.. we followed what exactly mentioned in here ( https://github.com/prologuetech/laravel-big ) during the installation.

**Comment by Medalink** [comment]
I updated the docs with the correct vendor:publish command.
