### ISSUE TITLE
Cannot run drop table command

### ISSUE THREAD

**Issue by hoanguel** [prologuetech/laravel-big#12]
Hi,

Whenever I do something like: `$big->run("DROP TABLE IF EXISTS myproject_id.my_dataset_id.my_table_name");` it will give an error message like this: `ErrorException: Undefined index: schema in /var/www/html/laravel/vendor/google/cloud/BigQuery/src/QueryResults.php:162`

All I want is to be able to drop a table if it exists or using 'CREATE OR REPLACE TABLE' DDL statement for the "createFromModel"  method. Any explaination / guide is much appreciated, thank you!

**Comment by Medalink** [comment]
@hoanguel Run assumes that you are running all queries against your default dataset ID within your config. To do so outside of that you may have to run that manually. A direct instance of the BigQuery client can be accessed via `$big->query`. Further you can run any manual BQ query with `$big->query->runQuery()`  see [the official google docs on it](https://googleapis.github.io/google-cloud-php/#/docs/google-cloud/v0.123.0/bigquery/bigqueryclient)

**Comment by hoanguel** [comment]
Hi, thank you Medalink! I figured out that for drop table statement you will need to pass the optional flags like these: `$big->run($drop_table_statement, NULL, FALSE);`
Hope that helps someone too!
