### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by ipansensoy** [prologuetech/laravel-big#2]
Hi documentation should be updated .. // Create our BQ helper
$big = new Big(); instantiating this into the controller is not allowed. do we need to add use on top?

**Comment by Medalink** [comment]
This depends on how you setup your ServiceProvider/Facade. Typically you will *want* a use at the top of your file: 

`use Prologuetech\Big;`

**Comment by hassanuos** [comment]
Can someone tell me why I am facing this issue everything is configured successfully?

![bq](https://user-images.githubusercontent.com/13483548/38372186-a86f4b0e-3907-11e8-81c9-7b4b5bb445a5.png)

**Comment by Medalink** [comment]
@hassanuos did you add `Prolougetech\Big\BigServiceProvider::class` to your Service providers in `config/app.php` ?

**Comment by hassanuos** [comment]
Yes, I already added that after that run the code. Everything I follow from the documentation. Thanks in advance @Medalink

**Comment by Medalink** [comment]
There was a typo in the package name, this is now resolved. Change any `Prolougetech` spellings to `Prologuetech` and update to the latest should fix issues.

**Comment by hoanguel** [comment]
I have exactly the same issue above, follow exactly all the steps given but it still same error. Almost give up but then try: **use Prologuetech\Big\Big;** and it works.
