### ISSUE TITLE
Handling of insertId's is causing false-positives

### ISSUE THREAD

**Issue by williamjulianvicary** [prologuetech/laravel-big#5]
The following line of code is checking in_array() to check for existence of an ID. This is actually checking the _values_ rather than the keys for the value. Would prefer an array_key_exists use here which would resolve the issue and allow a record with non-ID to work as intended.

https://github.com/prologuetech/laravel-big/blob/ee56839d52a71f36de3d0ca51d1252df220ffb0d/src/Big.php#L172

**Comment by Medalink** [comment]
Hmm, can you provide an example array of data you are using that does not work?

**Comment by williamjulianvicary** [comment]
The in_array statement is checking whether an array's values contain an 'id' value, whereby surely we want to check if the $item has a key of 'id' in this case?

**Comment by Medalink** [comment]
This is typically the data structure I work with that maps correctly:

```php
// Laravel collection arrays before ->prepareData()
[
    [
        'id' => '1',
        'short_name' => 'Kessler LLC',
    ],
    [
        'id' => '2',
        'short_name' => 'Typical Platforms',
    ]
];

// After ->prepareData()
[
    [
        'insertId' => '1',
        'data' => [
            'id' => '1',
            'short_name' => 'Kessler LLC',
        ],
        'fields' => [],
    ],
    [
        'insertId' => '2',
        'data' => [
            'id' => '2',
            'short_name' => 'Typical Platforms',
        ],
        'fields' => [],
    ]
];

// Without ID column selected and before ->prepareData()
[
    [
        'short_name' => 'Kessler LLC',
    ],
];

// Without ID column and after ->prepareData()
[
    [
        'data' => [
            'short_name' => 'Kessler LLC',
        ],
    ]
];
```

**Comment by Medalink** [comment]
Any updates on this? If you are passing in a single layer array I could see issues with this. Perhaps the code needs to account for that.

**Comment by williamjulianvicary** [comment]
Hey @Medalink I'll loop back when I can on this, I've had my head out of the code for a little while and I'm out of the office for a month as of the end of next week so it's all go at the moment!

**Comment by Medalink** [comment]
@williamvicary alright, I will close for now. Let me know if some adjustments are needed to better fit your use case.
